/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.todoapi.api;

import java.util.Optional;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import com.example.todoapi.common.model.dashboard.DashboardTaskListDto;
import com.example.todoapi.common.model.task.TaskListDto;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;

@CrossOrigin(origins = "http://localhost:4200")
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-09T15:53:29.993503800+09:00[Asia/Tokyo]")
@Validated
@Tag(name = "dashboard", description = "ダッシュボードのAPI")
public interface DashboardApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /dashboard : ピン留めタスク一覧取得
     * ピン留めしたタスクを4件取得します
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "dashboardTasks",
        summary = "ピン留めタスク一覧取得",
        description = "ピン留めしたタスクを4件取得します",
        tags = { "dashboard" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TaskListDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/dashboard/",
        produces = { "application/json" }
    )
    default ResponseEntity<DashboardTaskListDto> dashboardTasks(

    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"page\" : { \"offset\" : 6, \"size\" : 1, \"limit\" : 0 }, \"results\" : [ { \"compF\" : 5, \"pinF\" : 2, \"id\" : 5, \"title\" : \"title\", \"content\" : \"content\" }, { \"compF\" : 5, \"pinF\" : 2, \"id\" : 5, \"title\" : \"title\", \"content\" : \"content\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
