/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.todoapi.api;

import java.util.Optional;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.context.request.NativeWebRequest;

import com.example.todoapi.common.model.common.BadRequestError;
import com.example.todoapi.common.model.task.TaskListDto;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Size;

@CrossOrigin(origins = "http://localhost:4200")
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-03-17T08:54:47.507584900+09:00[Asia/Tokyo]")
@Validated
@Tag(name = "tasks", description = "タスク関連のAPI")
public interface TasksSelectListApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /tasks/ : タスク一覧取得
     * タスクの一覧を取得できます
     *
     * @param title タスクのタイトル (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     */
    @Operation(
        operationId = "listTasks",
        summary = "タスク一覧取得",
        description = "タスクの一覧を取得できます",
        tags = { "tasks" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TaskListDto.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/tasks/",
        produces = { "application/json" }
    )
    default ResponseEntity<TaskListDto> listTasks(
//        @NotNull @Min(1) @Max(100) @Parameter(name = "limit", description = "リストに含まれるリソースの最大値", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = true, defaultValue = "10") Integer limit,
//        @NotNull @Min(0L) @Parameter(name = "offset", description = "オフセット", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = true, defaultValue = "0") Long offset
        @Size(max = 256) @Parameter(name = "title", description = "タスクのタイトル", in = ParameterIn.QUERY) @Valid @RequestParam(value = "title", required = false) String title
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"page\" : { \"offset\" : 6, \"size\" : 1, \"limit\" : 0 }, \"results\" : [ { \"compF\" : 5, \"pinF\" : 2, \"id\" : 5, \"title\" : \"title\", \"content\" : \"content\" }, { \"compF\" : 5, \"pinF\" : 2, \"id\" : 5, \"title\" : \"title\", \"content\" : \"content\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
