version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./TodoApi-database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./TodoApi-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./  # 親ディレクトリを指定
      dockerfile: ./TodoApi-client/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata:
