services:
  db:
    image: postgres:15
    container_name: postgres_dev
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: tododb
volumes:
  db-store: